# Generated by Django 4.0.3 on 2022-04-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_project_created_project_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created'], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
    ]
